### ISSUE TITLE
avahi-daemon: invalid response packet from host

### ISSUE THREAD

**Issue by nickjmeyer** [ev3dev/ev3dev.github.io#123]
I'm able to get ev3dev loaded on an ev3 without any problem.  However, after the ev3 boots up, about 50% of the cpu is taken for system tasks.

```
top - 18:50:21 up 22 min,  1 user,  load average: 1.31, 1.20, 0.97
Tasks:  59 total,   1 running,  58 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.9 us, 56.3 sy,  0.0 ni, 41.9 id,  0.7 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem:     59436 total,    57632 used,     1804 free,     5068 buffers
KiB Swap:    98300 total,     1216 used,    97084 free.    31468 cached Mem
```

I checked `journalctl` and it shows that the avahi-daemon is having some errors.
```
Mar 07 18:51:00 ev3dev avahi-daemon[268]: Invalid response packet from host 10.139.101.26.
Mar 07 18:51:01 ev3dev avahi-daemon[268]: Invalid response packet from host 10.139.101.26.
Mar 07 18:51:02 ev3dev avahi-daemon[268]: Invalid response packet from host 10.139.101.26.
Mar 07 18:51:02 ev3dev avahi-daemon[268]: Invalid response packet from host 10.139.101.26.
```

After googling this error, it appears to be a known bug.  The bug reports say it has been fixed.  Though it appears that the version in ev3dev doesn't have the patch.  Any suggestions for how to proceed?

**Comment by dlech** [comment]
This is an issue tracker for our website. Please open this issue at <https://github.com/ev3dev/ev3dev/issues>. Also see <http://www.ev3dev.org/support/>.

**Comment by WasabiFan** [comment]
Ok, maybe I was too quick to suggest that we re-enable issues on this repo :wink: We should add an issue template here that advises people to see the support page and not post here.

**Comment by pursuitEvasionLegos** [comment]
Sorry about this...  I just punched "github ev3dev issues" and didn't realize I clicked the one for the website...

**Comment by nickjmeyer** [comment]
Sorry about this... I just punched "github ev3dev issues" and didn't realize I clicked the one for the website...

**Comment by WasabiFan** [comment]
I'm not saying that you did anything wrong -- we simply didn't document where people should open issues. It's totally understandable. I'm now trying to figure out how to remedy the issue so that others aren't mislead as you were.
