### ISSUE TITLE
github-cards need tweaking for horizontal layout

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev.github.io#139]
Example from http://www.ev3dev.org/docs/tutorials/setting-up-an-nfs-file-share/

![selection_002](https://cloud.githubusercontent.com/assets/963645/14764123/1f25443c-0972-11e6-86f0-a1c7a77858d4.png)

**Comment by WasabiFan** [comment]
Oh, I didn't realize that the user cards had been added to that PR. And honestly, I'm surprised they work at all in this view -- as far as I know they use 100% width. Whatever the case, it should be simple to add a width to those things.

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev.github.io/commit/93ae8d5712434af81d0ad5481a639ad0879974cb
