### ISSUE TITLE
"http://lab.open-roberta.org/" is throwing errors and failing the CI build

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#142]
Currently, CI builds fail with errors about not being able to access `http://lab.open-roberta.org/`. I tried it in multiple browsers locally and I can't access that URL either (it times out after a few minutes and displays a server error page). I'm pretty sure that this worked before, but it looks like they are having some severe server troubles.

For reference, this is the page that it brings me to after the timeout period:
<img width="786" alt="snip_20160424135704" src="https://cloud.githubusercontent.com/assets/3310349/14770364/bba84694-0a24-11e6-9c8b-f73db0960aec.png">

Also pinging @ensonic so he's aware, as this is generally his domain.

**Comment by ensonic** [comment]
Which CL build is it (got a link)? The service now switched to https://, but there should be redirects.

FYI: I am just a contributor, I am not owning this.

**Comment by ddemidov** [comment]
> Which CL build is it (got a link)?

I think its this one: https://travis-ci.org/ev3dev/ev3dev.github.io

**Comment by WasabiFan** [comment]
> FYI: I am just a contributor, I am not owning this.

Yep, I understand. I just want to make sure you are aware of this so that if you know things that we don't you can pass on that information. And if we determine that it is an unknown problem on their end, you probably know more about how to let them know than we do.

> The service now switched to https://, but there should be redirects.

As far as I can tell, it isn't accessible either way. Even from a browser, I wasn't able to get to that url with or without the `https`.

**Comment by WasabiFan** [comment]
Although, it just worked on my phone -- maybe they fixed it? Or maybe it's dependent on what infrastructure you hit along the way?

**Comment by ddemidov** [comment]
The link works for me, but the connection seems to be very slow. May be the server is stressed at the moment?

**Comment by WasabiFan** [comment]
I just triggered a restart of the [most recent build](https://travis-ci.org/ev3dev/ev3dev.github.io/builds/125460110) and it's happy now. Looks like whatever it was, it is either intermittent or resolved. Based on what I have seen, these symptoms align with a DDOS attack, so it's possible it will go back offline in the future (and that would explain the slowness).

I'll close this as the build is now working, but we should keep an eye on it just in case.

**Comment by ensonic** [comment]
Thanks! We've released 1.4 today and send out the announcements, maybe the server got overloaded a bit.
