### ISSUE TITLE
Links to Apple documentation from NFS tutorial are now broken

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#144]
The CI server is seeing a few broken links to Apple docs from the NFS tutorial. My guess is that these pages were moved around on Apple's side, because I can't access them from my browser either.

Relevant log section from build job:
```
- ./docs/tutorials/setting-up-an-nfs-file-share/index.html
  *  External link https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/nfsd.8.html failed: 404 No error
  *  External link https://developer.apple.com/library/mac/documentation/Darwin/Reference/Manpages/man5/exports.5.html failed: 404 No error
  *  External link https://developer.apple.com/library/mac/documentation/Darwin/Reference/Manpages/man8/showmount.8.html failed: 404 No error
```

[A search](https://developer.apple.com/search/?q=nfsd) on their site returns links to the right pages, but those links are the same as ours and hence broken. Maybe this is temporary (an accident)?

Pinging @antonvh -- do you know what these links should be pointing to now?

**Comment by WasabiFan** [comment]
It looks like their search system has re-indexed, and those pages are definitely gone now. Should we just remove those links? I imagine there's a replacement page somewhere, but I can't find it and would rather not leave public broken links.

**Comment by dlech** [comment]
If this is specifically related to OS X, then the equivalent BSD man pages should be an OK substitute.

https://lmddgtfy.net/?q=nfsd%20!bsdman

**Comment by dlech** [comment]
Actually, this site might be a decent alternative if the official apple pages don't pop back up soon

http://www.manpages.info/macosx/nfsd.8.html
