### ISSUE TITLE
author cards messed up

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev.github.io#151]
Example: http://www.ev3dev.org/news/2016/01/25/evb-ev3dev-jessie-2016-01-25-release/

Firefox 45 on Ubuntu 16.04

![selection_009](https://cloud.githubusercontent.com/assets/963645/15084668/9938a552-139a-11e6-9cc2-81cc41ab1fbe.png)

**Comment by WasabiFan** [comment]
I'm seeing the same issue in Firefox, but I don't see it in Edge and can't check in Chrome right now. I am sure that I tested the cards after my most recent style changes in Chrome, but I don't remember if I tried in Firefox. I'll take a look at this.
