### ISSUE TITLE
Odd logo background size in Firefox

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#166]
I just noticed an odd behavior of the darkened logo background on Firefox (both Ubuntu and Windows):
![screenshot from 2016-05-23 20 21 45](https://cloud.githubusercontent.com/assets/3310349/15491307/000557ee-2124-11e6-85c5-cb787d12e050.png)

The background in the upper-left corner is 90+ pixels instead of the expected 62. @dlech do you see the same? Tested in FF 37 and 44.

**Comment by dlech** [comment]
Looks good on FF 46.01 on Ubuntu 16.04

**Comment by WasabiFan** [comment]
Hmmm... My test cases were 37 on Ubuntu 15.04 and 44 on Windows 10.

**Comment by WasabiFan** [comment]
I'll try in an up-to-date version when I can and see if that makes a difference.

**Comment by WasabiFan** [comment]
Yeah, it seems to work in FF 45+. So whatever it is, it looks like it's been fixed in more recent versions of Firefox. Closing, as this shouldn't be an issue.
