### ISSUE TITLE
Project pages showing unrendered markdown

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#201]
Something we've done has broken the formatting on [the Treev3 project page](http://www.ev3dev.org/projects/2014/11/30/TreeV3/) as well as a few others. Some of the Markdown is rendering in HTML view as raw text instead of being converted to HTML tags.

**Comment by WasabiFan** [comment]
Turns out that this isn't just on one page; others are having the issue too. e.g. http://www.ev3dev.org/projects/2015/01/30/Snake-Game/

**Comment by dlech** [comment]
Probably just need to add `markdown="1" to the `div` tag [here](https://github.com/ev3dev/ev3dev.github.io/blob/master/_layouts/project.html#L5).

Also probably shouldn't indent `{{ content }}` otherwise the first line could be messed up.

**Comment by WasabiFan** [comment]
I had thought it was a markdown parser issue... turns out someone just had invalid kramdown in their page and then that page was copied to make another one. Problem solved!
