### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#219]
When we are writing markdown for the website, what line length should be wrap at?

I would vote for 120 or 130 characters, but I want to reach a decision and standardize.

**Comment by dlech** [comment]
I generally wrap to 80, mainly because that's what I am used to from other software projects. It has the advantage that is also works well with the side-by-side diff on GitHub.

**Comment by WasabiFan** [comment]
OK, I'll try to standardize to that. I guess I will need to increase my font size :laughing: On these high-res displays, 80 chars barely reaches across a third of the display!
