### ISSUE TITLE
Docker image used in docker tutorial fails to run

### ISSUE THREAD

**Issue by DEGoodmanWilson** [ev3dev/ev3dev.github.io#232]
Following the [Docker tutorial](http://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/), attempting to run the Docker image results in the following error:
```bash
$ docker run --rm -it -v /Users/dgoodman/Documents/Projects/ev3/:/home/compiler/example ev3cc
standard_init_linux.go:175: exec user process caused "exec format error"
```

Docker version 1.12.0, build 8eab29e on OS X 10.11.6

**Comment by WasabiFan** [comment]
See the warning (has the title "Linux") on the [tutorial page](http://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/). The solution is to install the `qemu-user-static` package.

In the future, please open issues that aren't related to site style or formatting on the main ev3dev repo: https://github.com/ev3dev/ev3dev

Maybe we need to make that box a warning (formatted orange with an exclamation point) so it's more noticeable; what do you think?

**Comment by DEGoodmanWilson** [comment]
Ah, yes, I see where I went wrong. I saw the title on that box, and assumed it was a special call out for people running Linux. Which it kind of is. Except I of course skipped it thinking it didn't pertain to me. I think that changing the heading to something like "Prerequisites" or similar might help a bit.

So, it sounds like this is a formatting issue after all, but I take your point about where to land these issues. Thanks for the prompt response!

**Comment by WasabiFan** [comment]
Oh, you're on OS X! In that case, please open an issue on the main ev3dev repo for the fact that our instructions aren't right for OS X, and link back to this issue. That box was intended, as the title suggests, just for Linux; I guess it didn't occur to us that the warning would apply to OS X too.

This could be considered a formatting issue, but it's a bit borderline; when in doubt, open it on the main repo.
