### ISSUE TITLE
Idea - Latest news (single) also on Home

### ISSUE THREAD

**Issue by bmegli** [ev3dev/ev3dev.github.io#272]
This is just an idea.

We could have the last of the latest news on the Home screen also, maybe with link `See More News`.

I am not sure about that, if it would fit graphically what we have now on Home.

Also the news sizes vary wildy.

I sometimes miss the news on ev3dev for a while just because they are not in Home section and I have to click through the News seciton.

**Comment by WasabiFan** [comment]
I like this idea. I played around with something like this a bit before, but haven't actually tried it out. One thing I was considering is being able to mark a news item as "featured" or similar: that way we can concentrate on only showing things that are important (e.g. Image and kernel releases).

**Comment by bmegli** [comment]
Or this could be only header of the [featured] latest news with read-more button.

The Home page already has quite a lot of information
