### ISSUE TITLE
python tutorial does not work on my ev3

### ISSUE THREAD

**Issue by Lennart99** [ev3dev/ev3dev.github.io#292]
This one:
http://www.ev3dev.org/docs/tutorials/setting-up-python-pycharm/

Making the clone works, but commit does not work.
I have git installed on both EV3 and the computer I am working on.

**Comment by WasabiFan** [comment]
We need to know _what_ doesn't work. What's the error and which step are you on?

**Comment by Lennart99** [comment]
for me the installation gone good, I made the clone for my development machine.
I have made the Python program, but "Commit and Push" does not work.
PyCharm says it had gone good, but the file does not exist on the EV3.
I hope you can help me.

**Comment by dlech** [comment]
* Try `git init myproject` after `mkdir myproject`
* Try running `myproject.git/hooks/post-receive` manually and see if there are errors.

**Comment by Lennart99** [comment]
I have get it to work!!🙂
I have done everything again with a new image
And it worked!

Thanks a lot!!
Lennart
