### ISSUE TITLE
Add info about the Lego Pixy to the existing camera tutorial

### ISSUE THREAD

**Issue by fisherds** [ev3dev/ev3dev.github.io#301]
Hey @dlech any chance you want to make a Lego Pixy tutorial and add that info to the bottom of the existing [camera tutorial](http://www.ev3dev.org/docs/tutorials/using-rpi-camera/)?  I need a camera solution for our class robots.  We use EV3 bricks not and RPi solution and Lego Pixy seems like the way I should go.

I noticed you added the driver info last year, 
[git commit](https://github.com/ev3dev/lego-linux-drivers/commit/d0d7c0623733e32187609f0d6d08167cff86d33b) but was a little worried to see it was untested. ;)

Info on the site:
http://www.ev3dev.org/docs/sensors/charmed-labs-pixy-cmucam5-for-lego/

I'm willing to play with it if you are willing to make some sample code for me to test.  At our school our old Arduino robot (based on the Sparkfun RedBot) used the Pixy and I'd like to keep using the Pixy on our new ev3dev robot plan.  I believe I can just buy one of these two adapters:
 - http://www.mindsensors.com/ev3-and-nxt/35-pixy-adapter
 - http://a.co/6wtHcnP
![pixylegocable](https://cloud.githubusercontent.com/assets/295078/20636129/3dafb41a-b335-11e6-9b91-965895c0f67a.png)

 then I just need to understand the code.  Love to get a head start from you Dave!

**Comment by WasabiFan** [comment]
I think it would make a lot of sense to have more complete camera documentation. Although I can't speak to the technical aspect of the Pixy, having a page with info for the RasPi cam, the Pixy and a standard USB webcam on one page would be really nice.

**Comment by dlech** [comment]
I would rather see each type of camera have it's own page. We can group cameras in a sub-category on <http://www.ev3dev.org/docs/tutorials>.

There is some exiting info about PixyCam on ev3dev already. The [driver page](http://www.ev3dev.org/docs/sensors/charmed-labs-pixy-cmucam5-for-lego/) and [this issue](https://github.com/ev3dev/ev3dev/issues/652).

The driver has been tested and fixed since the commit that you noted. 

There are two version of the PixyCam, the is just a "regular" PixyCam and there is "Pixy for LEGO". If you have the regular version, then, to use it as a LEGO sensor, you need the mindsensors adapter. IF you have the LEGO version, it should have come with the Pixy LEGO Mindstorms cable already. You should be able to use both models via USB as well (no adapter cable required). In fact, USB is needed to access some of the more advanced features of the PixyCam.

That is about the extent of my knowledge of the PixyCam with regard to ev3dev. I haven't really used it enough to write a decent tutorial.

**Comment by fisherds** [comment]
I tried using a Lego Pixy sensor with no luck at all.  @dlech am I doing something wrong or does the untested code not work?  :)   Using the current ev3dev image on an EV3 from 2016-10-17.  I'd prefer to use the phone jack connector instead of the USB, so I've got the Pixy in input port 2 using the cable that came with it (not the Mindsensors version).  I set the color with Pixymon so no issues there.  Playing with python here is my code:

```
import ev3dev.ev3 as ev3
import time

print("Example of a functional sensor (color in this case)")
color_sen = ev3.Sensor(driver_name="lego-ev3-color")
assert color_sen.connected
print(color_sen.modes)
print()
print("Attempt to use a Pixy")
pixy = ev3.Sensor(driver_name="pixy-lego")
assert pixy.connected
print(pixy.modes)

for _ in range(10):
    values = pixy.value(5)
    print(values)
    time.sleep(2)
```


The output is....

```
Example of a functional sensor (color in this case)
['COL-REFLECT', 'COL-AMBIENT', 'COL-COLOR', 'REF-RAW', 'RGB-RAW', 'COL-CAL']

Attempt to use a Pixy
Traceback (most recent call last):
  File "basic_test.py", line 11, in <module>
    assert pixy.connected
AssertionError
```

Without the assert it just crashes later of course.  It's just not finding the Pixy as a sensor.  Thoughts? I also tried ms-pixy-adapter.  I have both sets of hardware handy.  No luck and not enough knowledge to do any meaningful debugging.  Is there a way to debug my issue?  Happy to help just don't know where to start.  I could try getting a USB hub and putting my WiFi dongle into one port and Pixy into another to try using it via USB, but I really don't have much interest in that route given the inelegant wires.  Any advice @dlech ?

Reference page:
http://www.ev3dev.org/docs/sensors/charmed-labs-pixy-cmucam5-for-lego/

**Comment by fisherds** [comment]
I guess I just had to complain then it started working.  Well it was either the complaining or the reboot of my EV3.  After the reboot suddenly the same code was getting passed the assert line.  Once passed the assert I did some other fixing and things started working with the Lego Pixy camera.  New code...

```
import ev3dev.ev3 as ev3
import time

print("Example of a functional sensor (color in this case)")
color_sen = ev3.Sensor(driver_name="lego-ev3-color")
assert color_sen.connected
print(color_sen.modes)
print()
print("Use a Pixy")
pixy = ev3.Sensor(driver_name="pixy-lego")
assert pixy.connected
print(pixy.modes)
# pixy.mode = pixy.modes[1]

for _ in range(10):
    pixy.mode = "SIG1"
    print("SIG1 reading")
    print(pixy.num_values)
    print("value0: Count", pixy.value(0))
    print("value1: X", pixy.value(1))
    print("value2: Y", pixy.value(2))
    print("value3: Width", pixy.value(3))
    print("value4: Height", pixy.value(4))

    pixy.mode = "ALL"
    print("ALL mode")
    print(pixy.num_values)
    print("value0: Signature lb", pixy.value(0))
    print("value1: Signature hb", pixy.value(1))
    print("value2: X", pixy.value(2))
    print("value3: Y", pixy.value(3))
    print("value4: Width", pixy.value(4))
    print("value5: Height", pixy.value(5))

    time.sleep(2)
```

The output has now been upgraded to...

```
Example of a functional sensor (color in this case)
['COL-REFLECT', 'COL-AMBIENT', 'COL-COLOR', 'REF-RAW', 'RGB-RAW', 'COL-CAL']

Use a Pixy
['ALL', 'SIG1', 'SIG2', 'SIG3', 'SIG4', 'SIG5', 'SIG6', 'SIG7']
SIG1 reading
5
value0: Count 1
value1: X 166
value2: Y 76
value3: Width 81
value4: Height 150
ALL mode
6
value0: Signature lb 1
value1: Signature hb 0
value2: X 162
value3: Y 76
value4: Width 83
value5: Height 152
SIG1 reading
5
value0: Count 1
value1: X 198
value2: Y 78
value3: Width 72
value4: Height 147
ALL mode
6
value0: Signature lb 1
value1: Signature hb 0
value2: X 196
value3: Y 76
value4: Width 73
value5: Height 147
SIG1 reading
...
```

BTW as a reference for others if you try to use Pixymon at the same time as the EV3 (which technically should be possible)

![pixymon](https://cloud.githubusercontent.com/assets/295078/21078200/ffd12adc-bf34-11e6-81fe-9349750900c3.png)

It will not update your data values so make sure to unplug the mini USB.  Pretty cool though!  It's working.

**Comment by KWSmit** [comment]
I'm testing with PixyCam for LEGO too. Got several scripts right now and will start working on a tutorial.

**Comment by KWSmit** [comment]
Can’t this issue be closed since there is a Pixy/Pixy2 tutorial?
