### ISSUE TITLE
Update PS3 gamepad tutorial for Python 3 and newer hardware

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#321]
The "Bluetooth PS3 gamepad in Python" tutorial currently targets older the Python 2 ev3dev library and last-generation PS3 controller. It would be nice to update this to the most recent editions and make sure everything still works.

cc @antonvh

**Comment by dlech** [comment]
I just got a PS3 controller today. I'm going to go make sure it works for video games right now, but I might try out this tutorial sometime in the near future.

**Comment by antonvh** [comment]
Thanks for the heads-up. I was going to update it, but then BB8 wouldn't
balance with a BT controller turned on. It's just beyond the capabilities
of the EV3 brick...
