### ISSUE TITLE
Add proper descriptions for class documentation pages

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#349]
Currently, pages like that for the tacho motor class show up like this in search results:

> Tacho Motor Class Documentation. Kernel Drivers. Tacho Motor Class. This docs page is for kernel version 4.4.44-18-ev3dev-ev3.

That's pretty useless. We should see if we can add better descriptions for at least the most important classes.

**Comment by dlech** [comment]
I'm working on moving all of the driver docs to readthedocs.org infrastructure so that we can have multiple simultaneous version, etc. So, I don't think it is worth doing anything with this issue.

**Comment by WasabiFan** [comment]
That looks good to me; I never took the time to properly respond to that issue, but I concluded a while ago that it's impossible for us to maintain multiple versions of documentation on our site. Assuming you haven't done so already, if you give me info on how you're structuring the docs site (and/or access to the current instance) I can get it integrated into the main site nav.

**Comment by dlech** [comment]
Here is what I have so far: http://docs.ev3dev.org/projects/lego-linux-drivers/en/sphinx-doc/

My plan was just to make redirects for existing pages and have a link to `docs.ev3dev.org` and manage everything from there since readthedocs has built-in search.

**Comment by WasabiFan** [comment]
Looks good! I mainly want to make sure that we don't break any existing links to `www.ev3dev.org` proper (read: set up redirects). We also need to figure out how our existing search system works; one simple option is to provide a link to the RTD search page in our results view. Preferably, attempts to find the driver docs on our main website should still get you to the new location. There may also be the possibility of requesting search results from them; I'll have to look. It's nice to get the "clutter" of the low-level technical stuff grouped up and separated; _most_ people don't need it at this point.

We need to figure out how to wire up navigation; preferably, we can make the nav somewhat match the main ev3dev.org header and then have the links switch between the two (with icons for external links). Is there a Read the Docs theme that more closely matches our site theme?

P.S. Is there a way to make it so that `docs.ev3dev.org` links to something useful? Presumably you can create an `index.rst` file.
