### ISSUE TITLE
Load download button styles before API responds

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#358]
Currently, the download buttons are bare links until the GitHub API responds. It would be better if the buttons were styled as soon as the page loaded and then updated once the call returned.

**Comment by dlech** [comment]
Is this still the case?

**Comment by WasabiFan** [comment]
I'm not aware of any changes made to fix this, but a cursory test didn't seem to show this behavior. I also don't see any styling happening in the release callback. So perhaps this was before we transitioned to Bootstrap...

It's probably OK to close this.

**Comment by dlech** [comment]
I thought I saw the same thing yesterday. Thanks for confirming.
