### ISSUE TITLE
Doker/Docker-Toolbox differences with shared folders

### ISSUE THREAD

**Issue by AgentConDier** [ev3dev/ev3dev.github.io#365]
The ["Using Docker to Cross-Compile"](https://github.com/ev3dev/ev3dev.github.io/blob/master/docs/tutorials/using-docker-to-cross-compile.md) tutorial does not mention that there are different versions of Docker (Docker for Windows and Docker Toolbox). I have Win10 Home edition, so when I tried to install Docker for Windows, it told me to use Toolbox, because I didn't have HyperV. That worked fine, but it gave me the following error whe trying to run `docker run --rm -it -v C:\Users\myname\example\:/src -w /src ev3cc` (god, it takes minutes to load. This is 2017, if you start a program it has to work within 10 seconds!!):

`D:\Docker Toolbox\docker.exe: Error response from daemon: invalid bind mount spec "C:Usersmynameexample:/src": invalid mode: src.
See 'docker run --help'.` 

(lol it interprets \ as an escape character? \*changes \ to /\* Nope, still the same error)

Then it said that I had to allow shared drives. I thing: hey, that is probably my problem! But to allow shared drives you need the docker whale icon, which does not exist in Docker Toolbox. It took me literally days (admittedly- I didn't have that much time per day, but still...) to figure out that Docker Tolbox automatically shares your user directory (didn't check, maybe it works anywhere on you computer), but you have to write the paths in linux notation (`/c/Users/myname/ev3cc/example/`). Please add this to the tutorial to not discourage new ~players~ err... users?

**Comment by dlech** [comment]
Would you be willing to make a pull request to add this documentation?

**Comment by AgentConDier** [comment]
Done: #371
