### ISSUE TITLE
Executing  a Docker compiled file on the EV3

### ISSUE THREAD

**Issue by Master-Matt** [ev3dev/ev3dev.github.io#367]
Hello all. I'm trying to work in C/C++ with ev3dev. I've followed the docker tutorial and I have everything working, but when I copy the binary file to a directory on the ev3 in ev3dev and try to run it, I get the "This file is not a directory or an executable." error. Did I miss something? the tutorial makes it seem so easy.

**Comment by WasabiFan** [comment]
I expect that you need to mark the file as "executable" first. Run `chmod +x myfile` from an SSH session to do that. We may need to add that note somewhere.

This repository is specific to our website; in the future, you should open issues at http://github.com/ev3dev/ev3dev when you have an issue with ev3dev itself.

**Comment by Master-Matt** [comment]
Derp. This happened to me the first time when using Python. I should have wrote it down.

**Comment by WasabiFan** [comment]
No problem! Please close the issue if that solved it.

**Comment by Master-Matt** [comment]
Also, I was trying to look up some of my old posts, but the issues are closed. Is there a filter to find those?

**Comment by Master-Matt** [comment]
Whoops, sorry about that. I'm still getting used to github.

**Comment by dlech** [comment]
> Also, I was trying to look up some of my old posts, but the issues are closed. Is there a filter to find those?

This repository is specifically for our website. You are probably looking for <https://github.com/ev3dev/ev3dev/issues/created_by/master-matt> (you can search issues by author).
