### ISSUE TITLE
How do I enter the wifi password?

### ISSUE THREAD

**Issue by manifolded** [ev3dev/ev3dev.github.io#378]
Your instructions on how to use a Wi-Fi dongle don't cover how to enter a Wi-Fi password.  I'm faced with an empty text box and no keyboard.  Since the USB slot is now full I cannot tether the brick to my laptop.  I have no idea how to enter the password.  It would be great if the instructions gave some guidance on this point.

**Comment by WasabiFan** [comment]
Haha, @dlech maybe we need a visual hint :wink:

Press the middle "enter" button on the brick and it will bring up the on-screen keyboard.

**Comment by manifolded** [comment]
That did the trick.  Thank you so much @WasabiFan

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev/issues is our main place for tracking issues. please open a issue there if you have an idea how we could make it more obvious.
