### ISSUE TITLE
Section "Previewing your changes online" is unclear

### ISSUE THREAD

**Issue by JesApp** [ev3dev/ev3dev.github.io#387]
I think the section  "Previewing your changes online" of `README.md` has two problems:

1. It refers to `./publish <gh-user>` which should be `./publish.rb <gh-user>`.
1. The fact that it's a separate section from "Previewing locally (which contains all the ruby setup) suggests - at least to me - that ruby is not needed for previewing online. Unless I missed something, that's not true. Maybe reorder to make the ruby setup it's own section.

**Comment by WasabiFan** [comment]
Those both make sense to me. I think the latter problem is a result of the fact that the online preview originally didn't require Ruby, and we changed the methodology after originally writing the guide. Would you be able to open a PR for this? (You can make the edits directly from the GitHub website.) I think adding a sentence referencing the earlier section would be fine for the second issue.

**Comment by JesApp** [comment]
Thanks for your answer. I made a pull request. I don't know which parts of the ruby setup are relevant for the online preview, though. It's probably better to discuss that over in the [PR](https://github.com/ev3dev/ev3dev.github.io/pull/388).

**Comment by JesApp** [comment]
The PR has been merged, closing.
