### ISSUE TITLE
"Using Docker to Cross-Compile" tutorial refers to brickstrap

### ISSUE THREAD

**Issue by JesApp** [ev3dev/ev3dev.github.io#390]
The [Using Docker to Cross-Compile](http://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/) tutorial refers to brickstrap in the sentence "Then back in the brickstrap shell run gdb." This is the first and only mention of brickstrap in the tutorial, which makes sense since we are using docker instead.

I'd change it to say "Then back in the container run gdb.", but that is currently not working. See [this issue](https://github.com/ev3dev/ev3dev/issues/1027).

**Comment by dlech** [comment]
I have fixed this for ev3dev-stretch, but unfortunately ev3dev-jessie is broken in a way that can be easily fixed (ev3dev/ev3dev#1056).

**Comment by JesApp** [comment]
I am running the `ev3dev/debian-jessie-cross` container with `gdb-multiarch` in it and it is working just fine.

That being said, is there a reason why the tutorial is still referring to the `jessie` rather than the`'stretch` container? Maybe switching that is the solution here.
