### ISSUE TITLE
Add Prolog API to list of languages

### ISSUE THREAD

**Issue by maweki** [ev3dev/ev3dev.github.io#414]
We have created a Prolog API for ev3dev that we use in teaching. As the work has now been published, we want to make our API available to the world:

https://github.com/maweki/ev3dev-prolog

As it turns out, programming a robot using Prolog works surprisingly well, as was predicted 30 years ago (and not often translated into practive). If it is preferred, I can make a pull-request with the link.

**Comment by dlech** [comment]
Cool. Yes, please make a pull request.

One tip for your README, be sure to add `sudo apt update` to the install instructions. Many people don't know that you have to do that first or `apt install` will fail.

**Comment by maweki** [comment]
This is now done.
