### ISSUE TITLE
configuring apt to be able to installl software

### ISSUE THREAD

**Issue by guinea7pig** [ev3dev/ev3dev.github.io#447]
how would i configure apt so i can dowlad software, the only thing i want to instatt os neofetch and some other stuff any help would be nice

**Comment by dlech** [comment]
See step 6.1 on this page: https://www.ev3dev.org/docs/getting-started/

**Comment by guinea7pig** [comment]
it will sudo apt update fine i just want to to install software like nofetch or htop, but whene ever i do it it just reternes packeege  not found

**Comment by guinea7pig** [comment]
![Screenshot 2024-12-06 at 1 46 10 PM](https://github.com/user-attachments/assets/595b61b2-2020-4bde-a0a2-f38b450639dc)
i think these contain update and firmware not pakeges what would be the the directory for them i could just insert it here

**Comment by dlech** [comment]
It looks like these two packages were not added until buster, so won't be available for stretch.

https://packages.debian.org/buster/htop
https://packages.debian.org/buster/neofetch

**Comment by BertLindeman** [comment]
My sources.list:
```

deb http://archive.debian.org/debian/ stretch main contrib non-free
deb http://archive.debian.org/debian/ stretch-proposed-updates main contrib non-free
deb http://archive.ev3dev.org/debian stretch main
deb  http://archive.debian.org/debian stretch-backports main
```
htop and neofetch can be installed at my ev3 at stretch.
No guarantee of course 😄 

Bert

**Comment by guinea7pig** [comment]
got it go  work  thanks
